###List developers
GET http://localhost:3000/developers

###get developers
GET http://localhost:3000/developers/3

###create developers
POST  http://localhost:3000/developers
Content-Type: application/json

{ 
    "name":"julio",
    "email":"julio@gmail.com",
    "dateOfBirth":"1990-02-01"

}

###update developers
PATCH  http://localhost:3000/developers/1
Content-Type: application/json

{ 
    
    "email":"Cesar@hotmail.com",
    }

###delete developers
DELETE   http://localhost:3000/developers/1